# embulk gem install embulk-parser-none
in:
  type: file
  path_prefix: example/example.jsonl
  parser:
    type: none
    column_name: payload
out:
  type: bigquery
  mode: replace
  auth_method: json_key
  json_keyfile: /tmp/your-project-000.json
  dataset: your_dataset_name
  table: your_table_name
  compression: GZIP
  source_format: NEWLINE_DELIMITED_JSON
  auto_create_dataset: true
  auto_create_table: true
  schema_file: example/schema.json
  payload_column_index: 0
