in:
  type: file
  path_prefix: example/example.csv
  parser:
    type: csv
    charset: UTF-8
    null_string: 'NULL'
    skip_header_lines: 1
    comment_line_marker: '#'
    columns:
      - {name: date,        type: string}
      - {name: timestamp,   type: timestamp, format: "%Y-%m-%d %H:%M:%S.%N", timezone: "+09:00"}
      - {name: "null",      type: string}
      - {name: long,        type: long}
      - {name: string,      type: string}
      - {name: double,      type: double}
      - {name: boolean,     type: boolean}
out:
  type: bigquery
  mode: append_direct
  auth_method: json_key
  json_keyfile: example/your-project-000.json
  dataset: your_dataset_name
  table: your_table_name
  compression: GZIP
  source_format: CSV
  auto_create_dataset: true
  auto_create_table: true
  schema_file: example/schema.json
  delete_from_local_when_job_end: false
